require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Gemspec/RequiredRubyVersion:
  Enabled: false
